//test line
#ifndef ERROR_CODES_H
#define ERROR_CODES_H

// GPIO ERRORS
#define MAP_ERROR -1
#define WRONG_PIN -2
#define OFFSET_ERROR -3
#define NULLPTRERROR -4

// PIPE AND FILE ERRORS
#define MKFIFO_ERROR -10
#define PIPE_NOT_SET -11
#define ISTREAM_ERROR -12
#define MALLOC_ERROR -13
#define IEVENT_MALLOC_ERROR MALLOC_ERROR
#define IEVENT_NULLPTR -14
#define WRITE_ERROR -15
#define READ_ERROR -16
#define INVALID_FD -17

// MESSAGE QUEUE ERRORS
#define MESSAGE_RECIEVE_ERROR -20
#define INVALID_SV_KEY -21
#define INVALID_POINTER -22
#define CANNOT_OPEN_MESSAGE_QUEUE -23
#define MESSAGE_SEND_ERROR -24
#define INVALID_MESSAGE_QUEUE_ID -25
#define INVALID_MESSAGE_QUEUE_NAME -26
#define MESSAGE_TOO_LONG -27
#define UNKNOWN_TYPE -28 

// STARTUP ERRORS
#define TOO_FEW_ARGUMENTS -30

#endif
